export const MISSING_NA_CHART = {
    caption: "NA - values in count and percentage",
    drawcrossline: "1",
    yaxisname: "NA values in count",
    syaxisname: "NA values in percentage",
    showvalues: "0",
    labeldisplay: "rotate",
    plothighlighteffect: "fadeout",
    theme: "fusion",
    plotSpacePercent: 10,
    numVisiblePlot: "20",
    scrollheight: "10",
    flatScrollBars: "1",
    scrollShowButtons: "0",
    scrollColor: "#cccccc",
    showHoverEffect: "1",
    numDivLines: "5",
    sYAxisMaxValue: "100",
};